//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOFOY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime bookTime { get; set; }
        public int bookFood { get; set; }
        public int bookCafe { get; set; }
        public string bookDetail { get; set; }
        public string CustomerId { get; set; }
    
        public virtual CafeShop CafeShop { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
